name: ir-action

on:
  push:
    branches:
      - main
  workflow_dispatch:
  # schedule:
  #   # 定期実行する時間・・・①
  #   - cron: "0 22 * * *"

jobs:
  get-ir:
    runs-on: ubuntu-latest
    steps:
      - uses:
          actions/checkout@v3
          # set up chrome driver
      - name: Setting up chrome driver
        uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: "104.0.5112.101"
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python3 main.py
